name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Build
        uses: docker/build-push-action@v6.2.0
        with:
          context: .
          push: false
          tags: "ghcr.io/${{ github.repository_owner }}/private-demo:pr-${{ github.event.number }}"
